name = "schnoodle-api"
type = "webpack"
account_id = "592c9fbea53d793527cc6078b8fe4502"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
kv-namespaces = [
  { binding = "SCHNOODLE_GRAPHQL_CACHE", id = "e2cb423111ee4eaf8b686a44f0cc2385" }
]